TRUNCATE user_api.users;
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Maci Swanson', 'Mathematician', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Marlie Robinson', 'Electrician', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Mayra Gamble', 'Web Developer', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Lilah Green', 'Economist', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Deborah Lee', 'Elementary School Teacher', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Chanel Andrade', 'Loan Officer', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Arnav Sanchez', 'Software Developer', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Lindsey Mahoney', 'Database Administrator', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Rodrigo Griffith', 'High School Teacher', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Kolton Cross', 'Chemist', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Yair Conrad', 'Paralegal', 'https://i.pravatar.cc/300', 1);
INSERT INTO user_api.users (id, name, title, avatar, is_active) VALUES (default, 'Alex Wong', 'Cashier', 'https://i.pravatar.cc/300', 1);
